### ISSUE TITLE
You have an API key referenced here and that should be a secret. 

### ISSUE THREAD

**Issue by asheliahut** [jankaltenegger/SAM.gov-Webscraper#1]
https://github.com/jankaltenegger/SAM.gov-Webscraper/blob/bc578489575700d63c946b43eca77394f0c7b543/samgov-webscraper.gs#L68C103-L68C103

**Comment by jankaltenegger** [comment]
Thank you, I completely missed that!

**Comment by asheliahut** [comment]
@jankaltenegger also as a side note make sure to rebase it out of your commits and swap the API key out for a new one on your side. Who knows who has been abusing it potentially.
